version: '3.4'

services:
  dealsdray:
    image: dealsdray
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5174:5174
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
